import { createSlice } from "@reduxjs/toolkit";
const initialState = {
  jobCategory: [
    "Accounting",
    "Administrative",
    "Arts and Design",
    "Business Development",
    "Community and Social Services",
    "Consulting",
    "Education",
    "Engineering",
    "Entrepreneurship",
    "Finance",
    "Healthcare Services",
    "Human Resources",
    "Information Technology",
    "Legal",
    "Marketing",
    "Media and Communication",
    "Military and Protective Services",
    "Operations",
    "Product Management",
    "Program and Project Management",
    "Purchasing",
    "Quality Assurance",
    "Real Estate",
    "Research",
    "Sales",
    "Support",
    "Training",
    "Writing and Editing",
  ],
  degrees: [
    "Associate's Degree",
    "Bachelor's Degree",
    "Master's Degree",
    "Doctoral Degree",
    "Professional Degree",
    "High School Diploma",
    "Certificate",
    "Diploma",
    "Other",
  ],
};
export const preferencesSlice = createSlice({
  name: "preferences",
  initialState,
  reducers: {},
});
export default preferencesSlice.reducer;
